# Generated by Django 4.2.4 on 2023-09-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pld_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='plant_leaf_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='plants',
            name='prediction_result',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
