# Generated by Django 4.2.5 on 2023-10-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pld_app', '0005_remove_prediction_name_prediction_prediction_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('number', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('message', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
